pact-foundation/pact-python

README.md

Resolves #12
- Removed the section on running the mock service as that requirement was
removed in #8
- Expanded the README to include instructions on Ruby configuraiton which
should have been included in #8 
@mefellows @jslvtr 
@dhoomakethu I think this should cover the steps you took to get things working?

Update the developer instructions

---

CONTRIBUTING.md

This should help us resolve issues more quickly.

Add some guidelines for raising issues

---

pact/matchers.py

Fix json generation of SomethingLike

---

pact/test/test_verify.py
pact/verify.py

- If --pact-url is given a directory the contents of the directory is recursively searched for JSON files
- On Windows the Ruby pact verifier expects / path separators, so we convert backslash to forward
@mefellows @jslvtr

Resolve #22: --pact-url accepts directories

---

setup.py

Update to pact-ruby-standalone 1.29.2

---

pact/pact.py
pact/test/test_pact.py
pact/test/test_verify.py
setup.py

Happy Hacktoberfest!
Looking to contribute to one of my favourite libraries!
This PR fixes #89 
Note: `given` needs to be come in before all three mandatory fields do.

Changed given to be optional

---

setup.py

Attempt to convert to kwargs in setup for Pycharm

Converting to kwargs

---

pact/verify.py
tests/test_verify.py

Creating multiple options for custom headers

Added multiple click options for custom headers

---

.travis.yml
pact/pact.py
tests/test_pact.py
tox.ini

Allowed https communication to mock. Didn't fix tests

---

setup.py

Please expose the --log-dir and --log-level options to the native API.

feat: update standalone to 1.86.0

---

examples/e2e/tests/userserviceclient-userservice.json
pact/verify.py
tests/test_verify.py

Added logging params

---

.travis.yml
CONTRIBUTING.md
script/commit_message.py

ci: add check for commit messages

---

script/commit_message.py

fix: script up to search branches

---

requirements_dev.txt
setup.py

This was raised by snyk and has been causing local dev issues. Hopefully this fixes it

fix: issue originating from snyk with requests and urllib

---

pact/__version__.py
pact/cli/verify.py
pact/verify_wrapper.py
tests/test_verify_wrapper.py

* feat: Including new option to disable pending pacts

feat: No include pending

---

README.md

Docs: Update docs to reflect usage for native Python

---

README.md
pact/verifier.py

- `missing_files` was set twice, the second time is not used
- `provider_app_version` was set twice with the same value
- removed unnecessary brackets
- fix link for GitHub badge

fix: remove dead code

---

README.md

- Table was mismatched, cli args were the python args and some missing
- updated links to examples

chore(docs): update provider verifier options table

---

.github/labels.yml

Inadvertent alias definition and fix.

chore(labels): fix incorrect label alias

---

README.md

Fixing links to example tests in README

docs(readme): fix links to examples

---

.github/renovate.json

Update the Compatibility Suite submodule, and additionally enable renovate's support for git submodules. This is still in beta and therefore has to be enabled manually.
Regular CI/CD
None

chore: update submodule

---

.github/renovate.json

Update the Renovate configuration file to use Renovate's best practices.
Help ensure we manage dependencies better.
None

chore(deps): use renovate best practices

---

.markdownlint.yml
.pre-commit-config.yaml
CONTRIBUTING.md
README.md
RELEASING.md
docker/README.md
examples/README.md

Markdownlint checks Markdown files for simple issues and formatting. The markdownlint configuration ensures consistency with the existing editorconfig.
Another move towards ensuring consistency for all developers.
Regular CI/CD
None

chore(dev): add markdownlint pre-commit

---

pact/consumer.py

Thanks to @hwong557 for reporting these typos.
- Resolves: #511

docs: fix typos

---

hatch_build.py

Bump the bundled Pact Ruby Standalone
Regular maintenance
CI/CD
None

chore(deps): upgrade pact ruby standalone to 2.1.0

---

hatch_build.py
pact/v3/ffi.py
pact/v3/pact.py

Upgrade the Pact FFI library to 0.4.15
The latest version includes the ability to add matching rules to an interaction.
None so far, but required for #474
Prerequisite for #474.

chore(deps): upgrade pact ffi to 0.4.15

---

tests/v3/compatiblity_suite/test_v3_consumer.py

Implementing more of the compatibility suite.
Regular pipelines
- Closes #475

chore(tests): add v3 consumer compatibility suite

---

hatch_build.py

Add support for `musllinux_aarch64` wheels.
Support more platforms!
As part of wheel build
None

feat: add support for musllinux_aarch64

---

.github/workflows/build.yml

For some reason, the rebase done as part of #567 really did not go well,
and some entire steps were inadvertently replaced. It is my bad, and
here's another (and hopefully final) fix.
The workflow will tell.
- #567

chore(ci): another build pipeline fix

---

.github/workflows/build.yml

(yes..., I am facepalming at my typo)

chore(ci): typo

---

.github/workflows/build.yml
.github/workflows/test.yml

Concurrency group didn't quite work as planned, resulting in excessive CI usage.
To reduce CI usage.
Inspecting CI workflows
None

chore(ci): update concurrency group

---

tests/v3/compatibility_suite/test_v1_provider.py
tests/v3/compatibility_suite/test_v2_provider.py
tests/v3/compatibility_suite/test_v3_provider.py
tests/v3/compatibility_suite/test_v4_provider.py

There is an issue tracking this, and until it is resolved, may as well disable the tests.
To avoid polluting failures
In CI
- #639

chore(test): disable failing tests on windows

---

docs/blog/posts/2024/05-02 integrating rust ffi with pact python.md
mkdocs.yml

Add a new blog post detailing the inner workings for the Rust FFI.
For anyone curious, or anyone who is trying to use FFIs from Python.
None

Rust FFI Blog Post

---

.github/codecov.yml
.github/workflows/test.yml

Add codecov integration.
Improve test coverage by identifying areas which might currently be missed.
As part of CI
None

chore(ci): add codecov

---

.github/workflows/build.yml

Changes to build conditions resulted in a failed release of `v2.2.2`
Allow the release of `v2.2.2` to proceed
CI
None

chore(ci): tweak build conditions

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/codecov.yml
.github/labels.yml
.github/semantic.yml
.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/labels.yml
.github/workflows/smartbear-issue-label-added.yml
.github/workflows/test.yml
.github/workflows/triage.yml
.github/workflows/trigger_pact_docs_update.yml
.markdownlint.yml
.pre-commit-config.yaml
docs/blog/.authors.yml
examples/docker-compose.yml
mkdocs.yml
pyproject.toml
tests/v3/compatibility_suite/util/pact-broker.yml

Adding YamlFix to lint and format YAML files automatically.
Help ensure consistency of YAML files
As part of pre-commit and CI, no other test needed.
None

chore: add yamlfix

---

.github/renovate.json

Configure Renovate to automatically merge update PRs once requirements are met (requirements being that a review is received, and CI passes).
Simplify dev review time.

chore(ci): automerge renovate PRs

---

committed.toml

Committed helps ensure conventional commit conventions are followed, which then feeds into the changelog.
Help ensure the changelog remains relevant.
- None

chore: update committed configuration

---

.github/workflows/test.yml

Upload test results to CodeCov
It should (hopefully) help contributors manage test failures.
As part of CI.
None

chore(ci): upload test results to codecov

---

.pre-commit-config.yaml
biome.json

Update Biome to v2
Biome lints JS files
CI

chore: udpate biome

---

.github/workflows/build-cli.yml
.github/workflows/build.yml
.github/workflows/test.yml
.taplo.toml
pact-python-cli/.gitignore
pact-python-cli/pyproject.toml
pact-python-cli/src/pact_cli/__init__.py
pyproject.toml

Derive the version from VCS, specifically `pact-python-cli/*` tags.
Simplify the release process.
CI
- None

chore(cli): get version from vcs

---

pact-python-cli/hatch_build.py
pact-python-cli/pyproject.toml

Clean up the build script to make sure it is documented and easy to maintain.
Improve maintenance/documentation.
CI
None

chore(cli): cleanup build script

---

pact-python-cli/tests/test_init.py

Fix a flakey test which did not wait for long enough.
Improve the developper experience
CI
None

chore(cli): fix flakey test

---

.github/labels.yml

Update the labels to reflect the new state of this repository
Better tracking of issues and PRs

chore(ci): update labels

---

src/pact/_util.py

The exception will still bubble up; but given this function is typically used within state callbacks which have minimal handling, the logging is important for visibility.
Improve developer experience when/if there are any errors.

chore: log exceptions from apply_args

---

src/pact/_util.py

Improve logging from `apply_args`, in particular, just because an argument was not applied does not mean anything went wrong.

chore: improve logging from apply_args

---

src/pact/verifier.py

-   [x] I have read the [Contributing Guidelines on pull requests](https://github.com/pact-foundation/pact-python/blob/main/CONTRIBUTING.md#pull-requests).
-   [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
In most cases, a provider will want to verify Pacts against a branch, and publish against the same branch. Despite this, the branch in the broker selector and the branch in the publish options were entirely unrelated.
This PR now ensures they are linked so that they can be set through either option, and re-used automatically in the other.
If a branch is …

chore: set verifier branch same as publisher branch

---

.vscode/extensions.json
.vscode/settings.json

Add recommended settings and extensions for VSCode.
VSCode is a popular IDE, and this will ensure contributors have a better developer experience.

chore: add vscode settings and extensions

---

cliff.toml
pact-python-cli/cliff.toml
pact-python-ffi/cliff.toml

Update the Git Cliff configuration.
Improve the generated changelogs.

docs: update git cliff configuration

---

.github/workflows/test.yml

The spell checks are already covered through pre-commit.

chore(ci): remove spelling check

---

.pre-commit-config.yaml
README.md
mascot.svg

docs: add mascot

---

pact-python-ffi/pyproject.toml
tests/test_match.py

The version was always meant to be dynamic, but had to be fixed initially to bootstrap the process. This was inadvertently not removed.

fix(ffi): make version dynamic

---

tests/.ruff.toml
tests/compatibility_suite/test_v3_generators.py
tests/compatibility_suite/test_v4_generators.py
tests/compatibility_suite/util/__init__.py
tests/compatibility_suite/util/interaction_definition.py

Implement the generators-related compatibility suite.
- Resolves: #1182 
- Resolves: #1183

chore(tests): add generators to interaction defn

---

mkdocs.yml
pyproject.toml

Add `llms.txt` and `llms-full.txt` generation
Help parsing of contents specifically for LLMs.

docs: generate llms.txt
