pact-foundation/pact-python

.travis.yml, requirements_dev.txt
- Setup a Travis CI configuration to perform a "build" of pact-python
- Run the tests using tox in Python versions 2.7, 3.3, 3.4, 3.5, and 3.6.
@jslvtr I threw this together so I don't accidentally commit broken things. We should be able to expand it into a full build process as we go.
=> Add Travis CI build

.gitignore, .travis.yml, MANIFEST.in, Makefile, scripts/build.sh, setup.py
- Build process now downloads and prepares the Ruby applications like the NPM based Pact
- Resulting *.tar.gz now includes portable Ruby versions of Mock Service and Verifier
- The platform appropriate version is unpacked when a user installs pact-python
@mefellows @jslvtr 
This work is based on the work in [pact-provider-verifier-npm](https://github.com/pact-foundation/pact-provider-verifier-npm/tree/master/scripts) and [pact-mock-service-npm](https://github.com/pact-foundation/pact-mock-service-npm/tree/master/scripts) and packages the same 4 platforms of each as part of the Python tar file. This results in a fairly big file (nearly 70MB), but the only way I've spotted without requiring the user to have Ruby is to combine the mock-service and verifier into a single install so we can cut …
=> Package the Ruby Mock Service and Verifier

CHANGES.txt, Makefile, README.md, e2e/contracts/test_e2e.py, pact/__init__.py, pact/constants.py, pact/consumer.py, pact/pact.py, pact/test/test_constants.py, pact/test/test_consumer.py, pact/test/test_pact.py, requirements_dev.txt, setup.py
- pact-python now manages the mock service process
- Moved the project to version v0.2.0
resolves #5 and possibly #7 
@mefellows @jslvtr
=> pact-python manages the mock service

pact/pact.py
In playing with pact-python I found I was unable to generate a pact file with a body of 0 where the 0 wasn't already a string (e.g. it's a json-encoded response of the number 0). I believe this PR rectifies the issue.
=> Allow falsy responses (e.g. 0 not as a string).

pact/test/test_verify.py, pact/verify.py
The broker credential command line arguments of the Ruby verifier
do not expect the arguments to be prefixed with `pact`.
resolves #24 
@mefellows @jslvtr
=> Fix the use of broker credentials

.gitignore, README.md, pact/__version__.py, pact/test/test_verify.py, pact/verify.py
- Updated '--pact-urls' to be a single comma separated string argument
- Added '--pact-url' which can be specified multiple times
Fixing https://github.com/pact-foundation/pact-python/issues/21
Note that this will break any existing versions that are using multiple `--pact-urls` arguments
@matthewbalvanz-wf
=> Issue: Cannot supply multiple files to pact-verifier

pact/test/test_verify.py, pact/verify.py, setup.py
The pact-verifier has removed the need for passing `--provider-states-url` so we can now skip
passing it to the process. We will leave our option in place until version 1.0.0 to maintain
backwards compatibility for anyone who has scripted calling the Python code
@mefellows @jslvtr @bethesque
=> Resolve #17: Deprecate --provider-states-url

pact/pact.py, pact/test/test_pact.py, requirements.txt
The start/stop commands in pact-mock-service have trouble with Windows because
it does not exactly support SIGTERM. The simplest solution is to shift how pact-python
runs the mock service to:
- Start the mock service using the `service` command
- Keep track of the subprocess during pact execution
- Use the terminate options from Python's subprocess module to stop the mock service
@mefellows @jslvtr @bethesque
=> Move to using the `service` command with pact-mock-service

README.md
fix-setup-url-name isn't referenced anywhere in the code, the format provider-states-setup-url is used else where in the README.md.
This PR assumes that provider-states-setup-url is the correct name and makes usage the same throughout the doc.
=> make setup-url name format match above reference

README.md, pact/__init__.py, pact/matchers.py, pact/test/test_matchers.py
- This is step 1 of the rename, adding Like as a alias for SomethingLike
- SomethingLike will be removed in version 1.0.0
@jslvtr @mefellows @bethesque
=> Resolve #43: Rename SomethingLike to Like

e2e/contracts/test_e2e.py
For https://github.com/pact-foundation/pact-python/issues/56
=> Resolve #56: Fix incorrect indent on test_incorrect_number_of_arguments on test_e2e

requirements.txt
Fixes https://github.com/pact-foundation/pact-python/issues/47
=> Allow newer versions of requests

setup.py
I'd like to suggest this as a solution to #47, instead of the solution provided in #48.
`requirements.txt` and `setup.py`'s dependencies serve two different purposes for libraries. Ideally `setup.py` dependencies are as relaxed as possible while ensuring the library will work with those dependencies, and `requirements.txt` pins every library to a specific version (e.g. for testing purposes). [This blog post](https://caremad.io/posts/2013/07/setup-vs-requirement/) has a good explanation.
As such I'm recommending a move away from the "copy what's in `requirements.txt` into `setup.py` and use those dependencies.
Let me know what you think.
=> Relax version requirements in setup.py (vs requirements.txt)

pact/test/test_verify.py, pact/verify.py, setup.py
- Uses the options from the Ruby pact-verifier to print a command that can be used to rerun specific interactions.
- Updated to pact-ruby-standalone 1.8.0
@bethesque @mefellows @jslvtr
Resolves #44
=> Resolves #44: Output a rerun command when a verification fails

e2e/app.py, pact/pact.py, pact/test/test_pact.py
Added from_term processing of path property in the constructor of Request
=> Enable possibility to use Matchers in path property of Request class

README.md
As per https://github.com/pact-foundation/pact-provider-verifier/issues/19
=> docs: remove reference to v3 pact in provider-states-setup-url

Makefile, e2e/contracts/test_e2e.py, pact/pact.py, pact/test/test_pact.py, pact/test/test_verify.py, pact/verify.py, setup.py
Resolves #58 
- Pinned to pact-ruby-standalone 1.9.0
- Removed the payload to `/pact` of the pact-mock-service as its no longer required
- Added the option to specify pact URIs as arguments to be consistent with the Ruby verifier
- Added deprecation notices to `--pact-url` and `--pact-urls`
- Added `file_write_mode` to the Pact class to control how the mock service
writes files when tests are run in parallel
=> Resolves #58: Update to pact-ruby-standalone 1.9.0

Makefile, pact/test/test_verify.py, pact/verify.py
- When running the verifier Ruby stacks are hidden by default
- They can be shown again by passing `--verbose` on the command line
Resolves #59
=> Resolves #59 Hide Ruby stack traces by default

pact/pact.py, pact/test/test_pact.py
Modify Retry.total in Pact._wait_for_server_start to reduce the total
wait time from 54 minutes to about 25 seconds.
With a Retry.backoff_factor of 0.1 and 15 retries, the total wait time
before an error is `sum([0.1 * (2**(i - 1)) for i in range(16)])` which
is 3276 seconds or 54 minutes.
=> Reduce timeout in _wait_for_server_start to 25s

pact/pact.py, pact/test/test_pact.py
I was getting error while using pact-python in windows 10 'There was an error when stopping the Pact mock service.' Same code was running without any error in Ubuntu.
While digging a bit found out that checking  self._process.returncode != 0 does not work with windows as in my case windows was returning return code as 15.
So now for windows I am checking if process still exists using psutil.pid_exists to determine if mock service is stopped or not.
=> Added windows specific code to check if mock service is stopped.

pact/consumer.py, pact/test/test_consumer.py, requirements_dev.txt, setup.py
`Pact` accepts a `file_write_mode`, but `Consumer().has_pact_with` does not currently pass it to `Pact`
=> Pass file_write_mode to Pact

setup.py
Should address #112 
`platform.platform()` returns a macOS version, rather than a Darwin version as of python 3.8.  Both should match the 'osx.tar.gz' pact build.
=> match platforms like 'macOS-*' to osx suffix

README.md, pact/test/test_verify.py, pact/verify.py, setup.py
Closes #113.
This PR updates `pact-ruby-standalone` and expose the `—broker-token` option.
=> Expose —broker-token option

pact/pact.py, pact/test/test_pact.py
Minor fixes that didn't get pushed before #106 got merged.
* `publish()` method was looking to see if `self.broker_username` was set instead of `self.broker_password` when adding the `--broker-password` argument
* Documentation updated to reflect environment variables picked up by pact broker client
* Allow `publish()` to proceed if no pact broker base URL is provided, but `PACT_BROKER_BASE_URL` environment variable is set
* Add test regarding above code change
=> Updates to integrated pact broker client

setup.py
This is required so that SSL_CERT_FILE is respected when fetching pacts from a pact broker with a self signed certificate.
=> feat: update to pact-ruby-standalone-1.79.0

pact/pact.py
We have a name of consumer which is a string formatted as title: "Sample Project". It's contract file is being saved as "sample_project_….json". While publishing pact logic is looking for a name of contract file beginning with not normalized, but original consumer name. Therefore it does not find the file and exits with following message:
No value provided for required pact_files
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
File "/…/site-packages/pact/pact.py", line 260, in stop_service
self.publish()
File "/…/site-packages/pact/pact.py", line 193, in publish
.format(url))
RuntimeError: There was an error while publishing to the pact broker at ….
The pull request is a fix for that.
=> Fix missing normalization of consumer name while publishing pact

tests/test_constants.py, tests/test_consumer.py, tests/test_matchers.py, tests/test_pact.py, tests/test_provider.py, tests/test_verify.py
Moving the `test` dir that was previously part of the `pact` package into it's own module `tests`. This follows standard practice in python projects.
=> Move tests to standard tests dir

docker/README.md, docker/build.sh, docker/py27.Dockerfile, docker/py36.Dockerfile, docker/py37.Dockerfile, docker/py38.Dockerfile
Created some simple docker files and script to help create envs where not all python versions are available. Needs a bit of work but allows debugging of version issues. I could tweak this to publish containers with pact-python installed and published to pact-foundation?
=> Docker support for builds

examples/e2e/requirements.txt
A stray f was in examples/e2e/requirements.txt causing pip install to break
=> Remove typo from examples/e2e requirements.txt

.pre-commit-config.yaml, pact/cli/verify.py, pact/verifier.py, pact/verify_wrapper.py, requirements_dev.txt, tests/cli/test_verify.py, tests/test_verifier.py, tests/test_verify_wrapper.py
=> feat: Support pending Pacts

pact/verifier.py, tests/test_verifier.py
Complimenting https://github.com/pact-foundation/pact-python/pull/170, this PR allows to set `consumer_version_selectors` (as a list of python dicts) when instantiating a `Verifier` object, e.g:
```python
verifier = Verifier(
consumer_version_selectors=[{"tag": "main", "latest": True}],
)
```
=> feat(verifier): Allow setting consumer_version_selectors on Verifier

pact/cli/verify.py
`pact-verifier` sends POST requests when setting up the provider states.
=> docs: typo in pact-verifier help string: PUT -> POST

examples/message/tests/consumer/test_message_consumer.py, pact/message_pact.py
MessagePact was not passing the pact_dir to the publish() method. This caused tests to fail.
=> fix: passes pact_dir to publish()

pact/matchers.py, tests/test_matchers.py
This PR fixes the usage of `Format().timestamp`, `Format().date`, and `Format().time` by converting the datetime objects into string isoformat. See https://github.com/pact-foundation/pact-python/issues/228
=> fix: fix datetime serialization issues in Format

pact/cli/verify.py, requirements_dev.txt
Click 8.0 released on 11th of May caused a lot of
> ValueError: 'default' must be a list when 'multiple' is true.
Because setup.py specifies `click>=2.0.0` the new version is installed, so tests will fail. There is also the option to set max click version to 6.8, like in `requirements_dev.txt` but I think the fix is fairly easy: change the optional arguments from empty string to empty list.
=> fix: change option default from empty string to empty list (click 8.0.0 incompatibility)

MANIFEST.in, README.md, setup.py
This pull request modifies `setup.py` to allow for offline installation of this package.
In a corporate environment, it is very difficult to garner adoption of a product that is difficult to install in an offline environment. This PR hopes to smooth out that process.
Users can now install this package via `pip install pact-python --bin-path=/../../../` to prevent the installation process from trying to fetch binaries from github.com.
This seems to be a short term solution to https://github.com/pact-foundation/pact-python/issues/116. I am not sure whether the maintainers would want to close that issue or keep it open for the time being. As per @mefellows, "... the ideal state I think is that Python bundles the Ruby application into the package, so at install time no network is required." …
=> chore: Bundle all Ruby standalone binaries into wheel when deploying

setup.py
This should enable PACT_DISABLE_SSL_VERIFICATION=true for Pact broker verification.
=> chore(ruby): update ruby standalone

examples/broker/docker-compose.yml, pact/pact.py, tests/test_pact.py
Relating to this issue: https://github.com/pact-foundation/pact-provider-verifier/issues/74
Minor change and shouldn't happen if following examples etc but it doesn't help explain the problem currently.
Had some weirdness with docker timing I think, hence adding in the healthcheck which seems to have addressed it.
=> fix(consumer): ensure a description is provided for all interactions

pact/matchers.py, tests/test_matchers.py
Closes https://github.com/pact-foundation/pact-python/issues/241, wherein using bytes is not a valid option for either request or response content.
=> feat(matcher): Allow bytes type in from_term function

setup.py
See changelog [here](https://github.com/pact-foundation/pact-ruby-standalone/blob/master/CHANGELOG.md)
> [](https://github.com/pact-foundation/pact-ruby-standalone/blob/master/CHANGELOG.md#features)v1.88.83 (2022-03-15)
Features
gems
update to pact_broker-client (1.59.0) ([142fdd6](https://github.com/pact-foundation/pact-ruby-standalone/commit/142fdd6)[](https://github.com/pact-foundation/pact-ruby-standalone/blob/master/CHANGELOG.md#v18882-2022-02-21)[](https://github.com/pact-foundation/pact-ruby-standalone/blob/master/CHANGELOG.md#features-1))
> v1.88.82 (2022-02-21)
Features
gems
update to pact (1.62.0) ([eb8ae0f](https://github.com/pact-foundation/pact-ruby-standalone/commit/eb8ae0f)[](https://github.com/pact-foundation/pact-ruby-standalone/blob/master/CHANGELOG.md#v18881-2021-12-16)[ …
=> chore: update PACT_STANDALONE_VERSION to 1.88.83

Makefile, examples/message/tests/consumer/test_message_consumer.py
Current consumer message example publishes pact with the same version number twice, update the fixture to ensure pact only publish once.
=> chore(test): fix consumer message test

.flake8, pact/broker.py, pact/consumer.py, pact/message_consumer.py, pact/message_pact.py, pact/pact.py, tests/test_broker.py, tests/test_message_pact.py, tests/test_pact.py
https://github.com/pact-foundation/pact-python/issues/268
- Support publishing pacts with branch and a build_url. 
- Use auto_detect_version_properties flag to read branch information from CI. ~~Enable it by default~~
[broker url](https://bethtest.test.pactflow.io/overview/provider/User%20Service/consumer/UserServiceClient)
=> feat: Support publish pact with branch

.flake8, README.md, pact/cli/verify.py, pact/verifier.py, pact/verify_wrapper.py, tests/cli/test_verify.py, tests/test_verify_wrapper.py
https://github.com/pact-foundation/pact-python/issues/267
- Support verify with a provider branch
- Updated readme
[broken url](https://bethtest.test.pactflow.io/overview/provider/PythonUserService/consumer/UserServiceClient)
=> feat: Support verify with branch

pact/message_pact.py, tests/test_message_pact.py
* feat: allow multiple provider states to be defined in a pact
* feat: allow additional parameters to be passed in the provider state
Signed-off-by: Nuno Frias <nsfrias@gmail.com>
=> feat: Enhance provider states for pact-message

.github/workflows/build_and_test.yml, CONTRIBUTING.md, examples/consumer/requirements.txt, examples/fastapi_provider/requirements.txt, examples/flask_provider/requirements.txt, examples/message/requirements.txt, requirements_dev.txt, setup.py, tox.ini
- add python 3.11 to test matrix and setup.py
- describe classifiers and python version for pypi package
- replace yanked version of wheel with a more recent one
- use compatible dependency versions for Python 3.6
closes #311
closes #329
=> ci: add python 3.11 to test matrix

docker/README.md, docker/build.sh, docker/py310.Dockerfile, docker/py311.Dockerfile, docker/py37.Dockerfile, docker/py39.Dockerfile
This pull request introduces the ability to build Docker images for Python versions 3.9, 3.10, and 3.11. Additionally, it unifies the existing images to ensure consistency and maintainability. The documentation has been proofread for clarity and accuracy, and the build instructions have been updated to reflect these new changes.
=> feat(test): add docker images for Python 3.9-3.11 for testing purposes

README.md, pact/matchers.py, tests/test_matchers.py
This introduces `pact.Format.iso_8601_datetime()` method to match a string for a full ISO 8601 Date.
This method does not do any sort of date validation, only checks if the string is according to the ISO 8601 spec.
It differs from `pact.Format.timestamp`, `pact.Format.date` and `pact.Format.time` implementations in that it is more stringent and tests the string for exact match to the ISO 8601 dates format.
Without `with_ms` parameter will match string containing ISO 8601 formatted dates as stated bellow:
* 2016-12-15T20:16:01
* 2010-05-01T01:14:31.876
* 2016-05-24T15:54:14.00000Z
* 1994-11-05T08:15:30-05:00
* 2002-01-31T23:00:00.1234-02:00
* 1991-02-20T06:35:26.079043+00:00
Otherwise, ONLY dates with milliseconds will match the pattern:
* 2010-05-01T01:14:31.876
* …
=> feat: add matchers for ISO 8601 date format

pact/pact.py
We found that pact ignores the CORS parameter of the `Consumer.has_pact_with()` function.
If the CORS parameter is set to True `--cors=*` is appended to the list of commands for the external mock service.
The mock service itself already supports this parameter.
=> Fix CORS parameter not doing anything

MANIFEST, setup.py
https://github.com/pact-foundation/pact-ruby-standalone/blob/master/CHANGELOG.md#features
Which links to
https://github.com/pact-foundation/pact_broker-client/releases/tag/v1.68.0
* support Cirrus CI environment
* pact-broker --help command failed with Could not find command "__broker_base_url"
=> Chore/upgrade to pact ruby standalone 2.0.3

.editorconfig, .pre-commit-config.yaml
Without wanting to overload the pre-commit hooks, this adds a few checks on the commits to ensure validity of files.
More time-consuming checks for linting and formatting are done pre-push to avoid impacting the developer experience during local development. These are covered by `prettier` (for markdown, yaml, json, ...), `black` for Python and `ruff` for Python linting.
To help standardise formatting in the future, an `.editorconfig` file has also been added to the repository.
By virtue of using `pre-commit`, only modified files are checked which ensures older files are incrementally updated.
=> style: add pre-commit hooks and editorconfig

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature.yml, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
This PR overhauls the `contributing.md` file and also adds templates for GitHub issues. The changes are mainly taken from the (excellent) Docusaurus repository.
I realised while pushing the changes that I should have done a more extensive look at the other `pact-*` repos and try and ensure consistency. So happy to change things up as need be.
When it comes to reviewing the GitHub issue templates which combine YAML and Markdown, a semi-rendered version can be seen when browsing the branch: [`bug.yml`](https://github.com/pact-foundation/pact-python/blob/docs/contributing-md/.github/ISSUE_TEMPLATE/bug.yml) and [`feature.yml`](https://github.com/pact-foundation/pact-python/blob/docs/contributing-md/.github/ISSUE_TEMPLATE/feature.yml).
=> docs: contribution guideline

.github/ISSUE_TEMPLATE/feature.yml
The template was adapted from the amazing Docusaurus templates, and unfortunately a mention to Docusaurus was missed.
N/A
N/A
=> fix(github): fix typo in template

.gitignore
Update the root `.gitignore` file from the `github/gitignore` repo.
I noticed that some settings from Visual Studio Code which typically should have been in the list of changed files were absent. While updating the VSCode gitignore, I took the opportunity to cleanup/update the rest based on the upstream.
=> chore(gitignore): update from upstream templates

pact/broker.py, pact/consumer.py, pact/http_proxy.py, pact/matchers.py, pact/message_consumer.py, pact/message_pact.py, pact/message_provider.py, pact/pact.py, pact/provider.py, pact/verifier.py, pact/verify_wrapper.py
As work starts on the next major version of Pact for Python, we need to start warning users that the current version will be deprecated in the future.
This commit adds a warning to the top of all modules and standalone functions informing end-users of a major upstream change. While the class names themselves might remain, the way they are used may change to accommodate the changes brought by the move to the Pact reference library, and to accommodate versions 3 and 4 of the Pact specification.
Once the work on Pact Python v3 is complete, a thorough migration guide will be written and only those classes, methods and functions which are breaking will have a `DeprecationWarning` added.
Not Applicable
- Resolves #397
=> chore: add future deprecation warnings

.github/workflows/build.yml
When migrating the CI publish script, I unfortunately missed the environment which contains the PyPI credentials.
Just fixing a mistake.
None
=> fix(ci): add missing environment

.github/semantic.yml, .github/workflows/trigger_pact_docs_update.yml, .pre-commit-config.yaml, Dockerfile.ubuntu, README.md, RELEASING.md, docker/README.md, examples/README.md, run-docker.sh, script/commit_message.py, script/release_prep.sh
This commit fixes pre-commit linting and formatting issues. To avoid refactoring all of the existing Python code (which will is going to be deprecated), the pre-commit configuration has been updated to ignore these Python files.
All other changes in this commit are purely stylistic.
Fixing the existing lints (or ignoring files) is pre-requisite to eventually enabling the pre-commit checks in the CI workflow.
None
=> style: fix pre-commit lints

.cirrus.yml, .github/workflows/build.yml, .github/workflows/test.yml
Limit a number CI workflows to run only on finalised PRs, specifically excluding draft PRs.
Draft PRs are a great way of sharing work that is in progress, but not yet ready to be reviewed and merged. Running a large number of CI workflows every time the draft PR is updated creates unnecessary noise.
Furthermore, Cirrus CI has monthly limits, and the draft PRs really have no reason to use up these resources.
See #413 
- Resolves #411
=> Reduce CI Runs on Draft PRs

conftest.py, examples/conftest.py, pyproject.toml
Commits describe the individual changes:
-   fix(test): ignore internal deprecation warnings
-   chore(test): add pytest options in root
To help ensure there is a unified experience when running any/all tests,
we need to define this in the root directory. The rest of the
example-specific `conftest.py` can remain in `examples/conftest.py`.
Running `pytest` in the root directory will now correctly execute _all_
tests, including the examples.
-   chore: fix hatch test scripts
Hatch scripts allow for additional arguments to be specified through the
`{args:<default>}` placeholder. Unfortunately, this was not
automatically enabled.
In doing this, I have also simplified the scripts by moving some common
pytest options into pytest's own `addopts` option.
- Resolves #408
=> Fix hatch test scripts

.github/workflows/build.yml, hatch_build.py, pact/constants.py, pact/v3/__init__.py, pact/v3/ffi.py, pyproject.toml, tests/ruff.toml, tests/test_constants.py, tests/test_ffi.py
This PR sets the groundwork to use the FFI. It ensures that the FFI is built during the wheel creation process thereby avoiding runtime slowdowns.
I have made sure that the commits are self contained for the review process. The commit messages are:
-   **chore(ci): update build targets**
As the upstream Pact reference library has a different set of targets,
the build targets for this library have been updated to match. The most
significant change is the dropping is 32-bit architectures altogether.
This also adds a `musllinux` target (which was previously not
supported).
-   **feat(v3): add v3.ffi module**
This module provides a Python interface to the Pact library written in
Rust. For this first commit, only the `pactffi_version()` function is
implemented and tested.
In the transition to …
=> FFI Groundwork

.cirrus.yml, conftest.py, pact/v3/__init__.py, pact/v3/ffi.py, pact/v3/pact.py, pyproject.toml, tests/conftest.py, tests/v3/conftest.py, tests/v3/test_pact.py
Implements the core `Pact` class, along with a number of other classes required for this to all work.
No changes to the existing library, but introduces significant changes to `pact.v3`.
Unit tests have been included as part of this PR.
- Resolves: #382
As this PR is rather substantial, I have split some of the less consequential commits from the major commit (`feat(v3): implement pact class`). While the PR as a whole can be reviewed, I would recommend reviewing each commit individually.
=> Pact Consumer

.github/labels.yml, .github/workflows/labels.yml
This commit adds label synchronisation, pulling the labels from `pact-foundation/.github` and merging them with the labels in this repository's `.github/labels.yml`.
- Resolves: #428
=> chore: add label sync

.github/workflows/test.yml, examples/.ruff.toml, examples/conftest.py, examples/src/fastapi.py, examples/src/message.py, examples/tests/test_00_consumer.py, examples/tests/test_01_provider_fastapi.py, examples/tests/test_01_provider_flask.py, examples/tests/test_02_message_consumer.py, pyproject.toml, tests/v3/test_http_interaction.py
As there is a significant existing codebase which will eventually be deprecated, there is little benefit to applying formatting and linting rules to the files which are to be deprecated.
This commit configures Ruff, Mypy and Black to exclude files in the v2 codebase so that `hatch run lint` can function correctly. As a result, the linting in the CI workflow has also been enabled.
An equivalent was already implemented for the pre-commit hooks.
- Resolves #425
=> chore: enable lints fully

.pre-commit-config.yaml, pact/v3/_ffi.pyi, pact/v3/ffi.py
As part of this PR, the following related work has been added:
The Rust FFI is wrapped by the Python CFFI package and a `_ffi.cpython-*.so` binary library is created. The binary library functions at runtime as a Python module, but obviously cannot be edited to add type hinting.
Instead, it is possible to add a `_ffi.pyi` file which provides type hinting in a separate file to the core implementation irrespective of whether the implementation being a Python text file, or a binary library.
Done as part of the pre-commit hook
- Resolves: #435
=> Add FFI type hinting

pact/v3/ffi.py, tests/v3/test_ffi.py
- Add an `OwnedString` class
- Update type annotations for functions which return strings which must be freed.
A number of FFI functions return strings that are owned by the library and must be freed manually. Unfortunately, returning a `str` from a function would result in a memory leak, as the Python runtime would not know to free the string.
This commit adds an `OwnedString` class that wraps a `str` and a function that frees the string. The `__del__` method of the class calls the free function, ensuring that the string is freed when the object is garbage collected.
- Unit tests have been included
- Resolves: #437
=> feat(ffi): add OwnedString class

.github/workflows/build.yml, hatch_build.py, pyproject.toml
At this stage, Python 3.12 is not supported. There is a separate PR already resolving this, but it requires an update to a dependency.
The resolution of build issues with Python 3.12 uncovered another issue related to the bundling of Ruby. These have been resolved as well.
Make sure that the CI pipelines work again.
- Resolves: #442
- Superseded by: #405
=> chore: exclude python 3.12

pact/v3/ffi.py, pact/v3/pact.py, tests/v3/test_pact.py
This commit implements the methods for the Pact Handle class which correspond to the methods of the library which take `PactHandle` as an argument.
None affecting existing library.
Part of the Pact Handle implementation
Unit tests included.
- Resolves: #418
=> feat(v3): implement Pact Handle methods

pact/v3/ffi.py
The various Pact iterators are empty at this stage as the returned classes are not implemented. As a result, this merely tests that the FFI `*_next` functions return a null pointer which raises a `StopIteration` exception in Python.
Fix CI workflow
Has been tested locally
None
=> fix(v3): add __next__ implementation

examples/src/message.py
Fix an issue with an 'unknown action' error being raised due to the branch not returning from the function.
Fix CI workflows
Tested locally, and will be tested in CI
- Resolves #430
=> fix(example): unknown action

.github/workflows/build.yml
Firstly, this commits adds the building of a source distribution. When a Python package is installed, it is typically installed from a binary wheel and will fallback to the source distribution if it cannot find a matching wheel.
Additionally, I have created a new GitHub environment called `pypi` which stores a token authorising publication to Pact Python (and only Pact Python). The token is associated with my account, and will hopefully be replaced by trusted publishing soon (which bypasses tokens entirely).
For the time being, I will keep the old GitHub environments in case I need to use the secrets there, but once I have confirmed the new credentials work (or that we don't need credentials at all thanks to trusted publishing), then I will remove the secrets.
The automated publishing to …
=> chore(ci): revise pypi publishing

examples/tests/test_01_provider_fastapi.py, examples/tests/test_01_provider_flask.py, examples/tests/test_03_message_provider.py
-   [x] I have read the [Contributing Guidelines on pull requests](https://github.com/pact-foundation/pact-python/blob/main/CONTRIBUTING.md#pull-requests).
-   [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
Fixing typo in the examples 
It fixes a bug
Tested locally
- Resolves: https://github.com/pact-foundation/pact-python/issues/445
=> fix: provider verification should use publish_verification_results

.cirrus.yml, .github/workflows/build.yml, .github/workflows/test.yml, pyproject.toml
Update the build scripts to test and target Python 3.12 released on 2 October 2023. As the dependency on distutils has been removed already, there are no other changes required.
At present, this depends on a beta version of aiohttp. As a result, before this can be merged, we must wait for
As detailed in the linked issue.
The regular test suite will suffice. There is no change to the library code.
- Resolves #405
=> feat: add python 3.12 support

pyproject.toml
With the resolution of the upstream issue with psutil builds on Windows and PyPy, we can re-enable the building of wheels for this target.
Covered by CI
- Resolves: #446 
- Waiting on `v5.9.7` of psutil to be released.
=> chore(ci): re-enable pypy builds on Windows

.cirrus.yml, .github/workflows/test.yml, .pre-commit-config.yaml, CONTRIBUTING.md, Makefile, examples/tests/test_00_consumer.py, examples/tests/test_01_provider_fastapi.py, examples/tests/test_01_provider_flask.py, examples/tests/test_02_message_consumer.py, examples/tests/test_03_message_provider.py, pact/v3/__init__.py, pact/v3/ffi.py, pact/v3/pact.py, pyproject.toml, tests/v3/compatiblity_suite/test_v1_consumer.py, tests/v3/test_async_interaction.py, tests/v3/test_ffi.py, tests/v3/test_http_interaction.py, tests/v3/test_pact.py, tests/v3/test_sync_interaction.py
Ruff has included (for a few months now) a formatter functionality. The formatting and linting are entirely distinct functionalities, though both provided by Ruff. My experience so far has been that Ruff's formatting is very fast, and mostly matches Black's formatting.
Ruff is super fast ⚡
While Black is already very fast, using a single tool that is fast and consistent seems like a better option going forward.
Regular CI/CD
None
=> chore(dev): replace black with ruff

pyproject.toml
The test segment of the CIBuildWheel process was failing due to Rust not being available for the installation/building of `pydantic_core`.
This should resolve the issue by installing Rust in the Docker image just before the test step. This is only done on pypy Linux builds, as the other interpreters and platforms seem to be working fine.
To fix CI
Regular CI
None
=> chore(ci): fix pypy linux builds

pact/pact.py, tests/test_pact.py
-   [x] I have read the [Contributing Guidelines on pull requests](https://github.com/pact-foundation/pact-python/blob/main/CONTRIBUTING.md#pull-requests).
-   [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
Interactions are cleared not only at "verify" but also at the time of error while leaving with statement.
It's a bug fix. Without it failure in one test can mess with the other test.
Run failing code submitted in the issue #533 
closes #533
=> fix: ensure interactions are not left when exception occur inside with statement (#533)

hatch_build.py
Updates Ruby 3.3.0 (from Ruby 3.2.2) & OpenSSL 3.2.0 (from OpenSSL 1.1.1)
Drops requirement for bash 
See full changelog v2.0.1 -> v2.4.0
https://github.com/pact-foundation/pact-ruby-standalone/blob/master/CHANGELOG.md
=> chore(deps): update to pact-ruby-standalone-v2.4.0

hatch_build.py
re: https://github.com/pact-foundation/pact-ruby-standalone/pull/131
=> chore(deps): update to pact-ruby-standalone-v2.4.1

hatch_build.py, pact/v3/ffi.py, pact/v3/pact.py, tests/v3/compatiblity_suite/test_v3_consumer.py, tests/v3/compatiblity_suite/test_v4_consumer.py, tests/v3/compatiblity_suite/util/consumer.py
Implements the `V4/http_consumer.feature` compatibility suite.
Passing the compatibility suite in regular CI workflow
- Closes #476
=> V4 HTTP Consumer Compatibility Suite

.github/workflows/build.yml, .github/workflows/test.yml
Use a filter to target the latest stable version of Python when building wheels on PRs. Otherwise, the workflow takes an unnecessarily long amount of time to execute.
The workflow was unnecessarily slow.
CI
None
=> chore(ci): speed up wheels building on prs

src/pact/v3/__init__.py, src/pact/v3/interaction/__init__.py, src/pact/v3/interaction/async_message_interaction.py, src/pact/v3/interaction/http_interaction.py, src/pact/v3/interaction/sync_message_interaction.py
As a result, the following classes have been split into their own modules:
- `Interaction` -> `interaction/__init__.py`
- `HttpInteraction` -> `interaction/http_interaction.py`
- `SyncMessageInteraction` -> `interaction/sync_message_interaction.py`
- `AsyncMessageInteraction` -> `interaction/async_message_interaction.py`
I am also removing the exporting of `Interaction` within the root `pact.v3` module, as end-users should never be instantiating interactions directly.
The `pact` module was getting a little crowded, and I'm planning to add support for the providers now.
CI workflow
None
=> refactor(v3): split interactions into modules

src/pact/v3/ffi.py, src/pact/v3/pact.py, tests/v3/test_pact.py
Add new `.specification` attribute to the `Pact` class.
A recent FFI release added the functionality to retrieve the specification behind a `PactHandle`. Using this feature, it is now possible to get the specification of the current Pact.
Added in unit tests.
None
=> feat(v3): add specification attribute to pacts

.github/workflows/build.yml
The cibuildwheel process does a check that the wheels are valid, and also performs an installation of the wheel and a basic check that the import is working fine. It seems redundant to be doing a separate check.
This was intended in commit 9604839, but a rebase inadvertently re-introduced the check.
Speed up the pipeline.
Regular CI
- 02eab542cc667ac3d19bd6acaf0d7a4a0
- #567
=> chore(ci): remove check of wheels

.github/workflows/build.yml
This commit simply parallelises the `musllinux` and `manylinux` builds.
The building of the `aarch64` wheels takes a _very_ long time. Until such time that GitHub provides ARM Linux runners, we unfortunately have to resort to emulation.
This is made worse specifically for Linux due the doubling of the number of targets from having both `manylinux` and `musllinux` wheels.
Build pipeline in CI
None
=> chore(ci): speed up build pipeline

pyproject.toml
Fix a typo in the repository link.
=> docs: fix repository link typo

hatch_build.py, pyproject.toml
Have cibuildwheel clean the repository before each build.
In the release of `2.1.2`, it was discovered that [cibuildwheel](https://cibuildwheel.readthedocs.io/) does not clean the repository between each build. This resulted in each wheel containing the binary artifacts of all previous wheels; resulting in in unnecessarily bloated wheels.
Tested locally
None
=> chore(ci): clean wheels

pyproject.toml
Rust needs to be manually installed within the pypy build image; however, with the addition of `before-build`, it would appear that the existing `before-build` no longer works.
The installation of the Rust toolchain has been moved to the `before-all` step.
Fix the PyPy wheels.
CI
None
=> chore(ci): fix pypy before-build

pyproject.toml
The `rm` and `mv` commands don't work well within Windows' default shell. As a result, a separate script for Windows is required.
Avoid bloat on Windows too (it is fixed for Linux and macOS).
CI
None
=> chore(ci): adapt before-build for windows

pyproject.toml
Unfortunately, pytest-bdd is not yet compatible with some of the internal changes introduced in PyTest 8.1.
Fix CI
CI
None
=> fix: delay pytest 8.1

src/pact/v3/__init__.py, src/pact/v3/ffi.py, src/pact/v3/verifier.py, tests/v3/assets/pacts/basic.json, tests/v3/test_verifier.py
Groundwork to be able to verifier HTTP pacts.
Part of the work for V3
CI Workflow
- #381
=> Groundwork API for Provider

pyproject.toml
- Rename development-only dependency group to use a common `devel-` prefix.
- Minor reformatting
This helps ensure that end-users don't get confused. For example `pact-python[types]` might indicate a new feature which supports typing (which it does not).
None
=> chore(deps): refactor dependencies

tests/v3/compatibility_suite/test_v1_consumer.py, tests/v3/compatibility_suite/util/__init__.py
With upstream changes resolving the underlying issue, these tests can be re-enabled.
Improved test coverage
As part of CI
None
=> Re-enable tests

src/pact/v3/pact.py, tests/v3/test_http_interaction.py
If the Pact Server exits with mismatches, an error is raised. In addition, the mismatches are exported as a JSON to the logger. This new behaviour can be disabled by setting `verbose=False` when starting the server.
Improved end-user experience to see the mismatches (and fix them).
Unit test added
None
=> feat(v3): add verbose mismatches to logging

pyproject.toml
Fix a missed renaming of `test` to `devel-test` in the optional feature groups.
Hatch test matrix doesn't work otherwise.
Tested locally
None
=> chore: fix missed s/test/devel-test/

pyproject.toml, tests/v3/compatibility_suite/util/__init__.py
Improve test logging
Improved debugging experience
None required
None
=> Improve test logging

.github/workflows/test.yml, conftest.py, pyproject.toml, src/pact/v3/ffi.py, src/pact/v3/verifier.py, tests/v3/compatibility_suite/definition-update.diff, tests/v3/compatibility_suite/test_v1_provider.py, tests/v3/compatibility_suite/util/__init__.py, tests/v3/compatibility_suite/util/pact-broker.yml, tests/v3/compatibility_suite/util/provider.py
Implement the `V1/http_provider` compatibility suite.
The majority of the changes are restricted to the tests folder, though a couple of fixes to the `v3` module have been introduced (see individual commits).
Ensure consistency with other Pact implementations.
Through CI
- Resolves: #469
=> V1 provider compatibility suite

tests/v3/compatibility_suite/conftest.py, tests/v3/compatibility_suite/definition-update.diff, tests/v3/compatibility_suite/test_v1_provider.py, tests/v3/compatibility_suite/test_v2_provider.py, tests/v3/compatibility_suite/test_v3_provider.py, tests/v3/compatibility_suite/test_v4_provider.py, tests/v3/compatibility_suite/util/__init__.py, tests/v3/compatibility_suite/util/provider.py
Implement HTTP provider compatibility suite for Pact specifications 2, 3 and 4.
To help ensure consistency across Pact implementations.
As part of CI
- Closes: #470 
- Closes: #471 
- Closes: #472
=> HTTP Provider Compatibility Suite

hatch_build.py, src/pact/v3/ffi.py, src/pact/v3/interaction/_base.py, src/pact/v3/interaction/_http_interaction.py
Upgrade FFI to `0.4.19`.
Most relevant for Pact Python is a fix to passing through binary bodies which would be dropped by Python before the FFI has a chance to properly parse the contents.
=> feat: upgrade FFI to 0.4.19

.github/workflows/test.yml
Use `macos-13` for Python 3.8 and Python 3.9, and `macos-latest` for all other Python version.
The GitHub runners behind `macos-latest` were recently upgraded to `macos-14` running on ARM / M1 architecture. Unfortunately, Python 3.8 and 3.9 aren't supported on ARM.
CI
=> ci: fix macos-latest

CONTRIBUTING.md
adds step to patch the compatibility suite in order for tests to pass
-   [x] I have read the [Contributing Guidelines on pull requests](https://github.com/pact-foundation/pact-python/blob/master/CONTRIBUTING.md#pull-requests).
-   [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
-   [x] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.
adds step to patch the compatibility suite in order for tests to pass
Cloned the repo for the first time and tried to run tests but some are failing. I found that the patch command is running within the github actions workflow to make the tests pass.
=> docs(CONTRIBUTING.md): update installation steps

.github/renovate.json
Group renovate updates across pre-commit and explicit dependencies.
Help reduce a little bit of the noise from Renovate, but more importantly, ensures that the pre-commit hook uses the same version as the dependency in `pyproject.toml`.
None
=> chore: group renovate updates

.github/workflows/docs.yml
With this change:
- Docs are built on pushes to `master`, PRs targetting `master`, and when new `v*` tags are pushed.
- Docs are published only when new `v*` tags are pushed (in line with new releases).
Reduce the noise of 'releases' on Slack which thinks that every update to the docs is worthy of a notification.
None
=> ci: narrow when docs are built and published

pyproject.toml
[uv](https://github.com/astral-sh/uv) provides similar capabilities to `pip` and `venv`, but is _significantly_ faster. Since `hatch` now supports using `uv` under the hood when managing virtual environments, we can get the speed ups for free.
To provide a better contributor experience.
Regular CI
N/A
=> chore: use uv to install packages

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature.yml, CONTRIBUTING.md
Update GitHub issue templates:
- Remove links to Canny
- Minor rewording
- Allow blank issues (in case someone really doesn't want to use a template)
Hopefully a better contributor experience.
None
=> chore: update GitHub templates

.github/workflows/build.yml
Disabling Windows ARM wheels builds as they are currently not working.
So that the release process can complete.
Regular CI
=> chore(ci): disable windows arm wheels

.github/workflows/build.yml
Removing the password, as it should not longer be needed now that trusted publishing is enabled.
Trusted publishing doesn't rely on an individual's API key, and instead delegates the authorisation to publish to the specific workflow.
As this is a release process, this will be verified at the next release 🤞 
None
=> chore(ci): use pypi trusted publishing

tests/v3/compatibility_suite/test_v3_http_matching.py, tests/v3/compatibility_suite/util/interaction_definition.py
-   [x] I have read the [Contributing Guidelines on pull requests](https://github.com/pact-foundation/pact-python/blob/master/CONTRIBUTING.md#pull-requests).
-   [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
Adding a v3 compatibility test for the http_matching feature. This seemed like an easy add since there were no code changes outside of testing code required.
Since I want to work on V3 matchers, my motivation was to learn a little more about how matchers work and move the overall V3 compatibility forward.
=> adding http_matcher.feature v3 compatibility test

.github/renovate.json
There appears to have been a change in the way renovate names packages.
Avoid the noise and possible incompatibilities due to having different versions of Ruff in the pre-commits and the dev dependencies.
CI
None
=> chore: regroup ruff in renovate

.github/workflows/build.yml, .github/workflows/test.yml, .pre-commit-config.yaml, CHANGELOG.md, CONTRIBUTING.md, biome.json, committed.toml, docs/blog/posts/2024/05-02 integrating rust ffi with pact python.md, docs/provider.md, docs/scripts/python.py, pyproject.toml, src/pact/matchers.py, src/pact/message_consumer.py, src/pact/message_provider.py, src/pact/v3/ffi.py, src/pact/v3/interaction/_http_interaction.py, tests/test_verifier.py, tests/v3/compatibility_suite/test_v3_message_consumer.py, tests/v3/compatibility_suite/util/interaction_definition.py
Add a few extra checks:
- Typos
- All `pre-commit` checks
Also refactor the test CI workflow
Help improve the code quality in the long run.
CI
None
=> chore: add extra checks

.pre-commit-config.yaml, examples/.ruff.toml, examples/src/consumer.py, examples/src/fastapi.py, examples/src/flask.py, examples/tests/test_00_consumer.py, examples/tests/test_01_provider_fastapi.py, examples/tests/test_01_provider_flask.py, examples/tests/v3/conftest.py, examples/tests/v3/test_00_consumer.py, examples/tests/v3/test_01_fastapi_provider.py
1. Added the http post and delete methods
2. updated the methods in v2 examples to verify the teardown
3. added new endpoints in flask and fastapi
Provide more realistic examples for pact-python
Examples are inherently tested
#757
=> Add Http Post and Delete examples

examples/docker-compose.yml
-   [x] I have read the [Contributing Guidelines on pull requests](https://github.com/pact-foundation/pact-python/blob/master/CONTRIBUTING.md#pull-requests).
-   [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
This is a fix to the docker-compose file, so that the examples do run correctly with the broker.
There are 3 smaller fixes in the PR, submitted in 3 commits.
I was trying to get the broker tests running and they would always fail because the broker would not start correctly. After this changes all works fine and I can continue to learn about …
=> fix and improve examples docker compose file

examples/tests/v3/test_00_consumer.py
-   [x] I have read the [Contributing Guidelines on pull requests](https://github.com/pact-foundation/pact-python/blob/master/CONTRIBUTING.md#pull-requests).
-   [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
As matchers are now supported in the V3 code, use them in the consumer example.
simplifying the examples
together with #808 run `hatch run example`
=> chore: use matchers in v3 examples

src/pact/v3/error.py, src/pact/v3/interaction/_base.py, src/pact/v3/interaction/_http_interaction.py, src/pact/v3/pact.py, tests/v3/compatibility_suite/util/consumer.py, tests/v3/test_error.py, tests/v3/test_http_interaction.py
Adds a `Mismatch` class and a number of subclasses.
This is done to facilitate the error handling, and error displays.
- The type of the mismatches in the `MismatchesError` is now different. It was a `dict[str, Any]` and is now a `Mismatch` sub-class.
Improve error messages, as the old error messages were clearly not appropriate.
At time of writing, yet to be done.
- Resolves: #644
=> feat: improve mismatch error

examples/conftest.py
Disable the use of `--wait` as it is incompatible with Podman (if someone is using `podman-compose` instead of `docker-compose`)
Ref: containers/podman-compose#710
Improve compatibility
CI
None
=> chore: disable wait

.github/workflows/build.yml, .github/workflows/docs.yml, .github/workflows/test.yml
We were still using the actions/setup-python action, which does not properly support uv (especially caching). We switch instead to `astral-sh/setup-uv` and use uv to manage Python version as well.
Improve CI performance
As part of CI
None
=> chore(ci): switch to uv fully

.github/workflows/docs.yml
Since the dogs are updated with all updates to `master`, it is redundant to also run the workflow for tags.
This was left-over from a time when the docs were only updates with releases.
Lessen CI workload
CI
None
=> chore(ci): disable docs workflow on tags

pyproject.toml
It would appear that PyPy builds with CFFI are broken (once again).
This was surfaced when trying to do a release for `v2.2.2` targeting PyPy on Windows.
CI (with a temporary commit)
None
=>  chore: disable pypy builds

src/pact/__init__.py
Accidentally included an incorrect URL
To have accurate metadata
None (trivial change)
None
=> chore: fix __url__

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature.yml, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/build.yml, .github/workflows/docs.yml, .github/workflows/labels.yml, .github/workflows/test.yml, .github/workflows/trigger_pact_docs_update.yml, CONTRIBUTING.md, README.md, docs/provider.md, docs/releases.md, docs/scripts/markdown.py, docs/scripts/python.py, pyproject.toml
Renamed the old `master` branch to `main` to align with new standards, this makes the corresponding changes in all files.
None, unless someone was relying on the `master` branch naming.
To align with new git standard.
CI
None
=> chore: rename master to main

.github/workflows/test.yml
Replacing with a manual installation and run of pre-commit, and `pre-commit/action`.
Maintainer of `pre-commit/action` does not want any PRs, and this will speed up CI.
As part of CI 
- pre-commit/action#218
=> chore(ci): replace pre-commit/action

src/pact/v3/pact.py
The arguments to `__exit__` are not used. When first implemented, this used the leading underscores to make that explicit; however, this is incompatible with the expected type signature of the function.
The PactServer `__exit__` arguments no longer have leading underscores. This is typically handled by Python itself and therefore is unlikely to be a change for any user, unless the end user was calling the `__exit__` method explicitly _and_ using keyword arguments.
Better compatibility with the expected behaviour of `__exit__`
CI
None
=> chore(v3)!: remove unnecessary underscores

examples/tests/v3/provider_server.py, src/pact/v3/_util.py, src/pact/v3/generate/__init__.py, src/pact/v3/match/__init__.py, src/pact/v3/pact.py, src/pact/v3/util.py, tests/v3/compatibility_suite/util/provider.py, tests/v3/test_pact.py, tests/v3/test_util.py
The `pact.v3.util` module contains useful utility functions used internally, but otherwise should not be used by Pact Python end-users. As a result, I am making it private now.
- `pact.v3.util` is renamed to `pact.v3._util`
- Functions within said module have had their leading underscores removed
Furthermore, as `pact.v3._util` is now a private module, breaking changes to private functions will _not_ be considered breaking changes to the Pact Python library.
Simplify the ongoing maintenance of the utility functions without burdening ourselves with backward compatibility.
Regular CI
None
=> chore(v3)!: make util module private

.github/workflows/test.yml, examples/conftest.py, pyproject.toml
Parallelise the tests so the test suite runs faster.
Better developer experience
CI
- https://github.com/pytest-dev/pytest/discussions/13056
Waiting on an answer as to whether it is possible to print a warning early in Pytest.
=> chore: add pytest-xdist

docs/blog/posts/2024/12-30 functional arguments.md
Version 2.3.0 of Pact Python adds support for functional arguments in a few Verifier methods. This blog posts documents the changes and how they can be used. It also documents the breaking changes that were introduced.
To help those users using the `pact.v3` module already, despite it not being stable.
- #890
=> docs(blog): add functional arguments post

.github/workflows/build.yml
This reverts commit 15f61caeb9dfa829b4548895b2deb1c9dda54f82.
There's a bug in softprops 'action-gh-release' action which appears when uploading larger assets. Reverting to an earlier version until fix is merged.
Ref: softprops/action-gh-release#562
Ref: softprops/action-gh-release#556
=> Revert "chore(deps): update softprops/action-gh-release action to v2.2.0"

src/pact/v3/verifier.py
Defer setting the Pact broker source through the FFI until the `verify()` call is made.
When setting that Pact broker source, the verifier name _must_ be set; however, the FFI call to set this is deferred until the `verify()` call. The setting of the Pact broker source (which itself depends on knowing the verifier name) must therefore be also deferred.
- Fixes: #931
=> fix(v3): defer setting pact broker source

.github/workflows/build.yml
Update the Ubuntu runners to 22.04 due to GitHub sunsetting the 20.04 runners.
To ensure that our CI workflows keep working.
As part of CI.
None
=> chore(ci): update ubuntu runners

.github/renovate.json
Reduce noise from the `taiki-e/install-action` dependency by having weekly updates only.
The `taiki-e/install-action` has _very_ frequent updates (due to updating the packages it knows about). This can result in sometimes multiple updates a day.
Having a weekly update should be plenty sufficient.
Renovate will validate the config. No other testing required.
None
=> chore: reduce noise from taiki-e/install-action

.github/workflows/test.yml
Pre-commit does not clean up any files, resulting in the cache bloating indefinitely if the cache is restored from a previous key. With this change, the pre-commit cache is cleared whenever the pre-commit config is updated.
=> chore(ci): remove pre-commit cache restore key

src/pact/v3/interaction/_sync_message_interaction.py
Add `will_respond_with` method for synchronous interactions.
HTTP interactions have a `will_respond_with` method which sets the response HTTP status code, and is used by the API to separate the request portion from the response.
While synchronous message interactions don't have a HTTP status code, an equivalent method is still useful within the API as it provides a way to separate the request and response logically, as opposed to required explicit stipulations every time.
None for now, but the plan is to add a gRPC example which will feature this.
None
=> feat(v3): add will_respond_with for sync

.github/workflows/build.yml
Update the CI runners to their latest versions.
Unblock CI due to the retiring of Windows 2019 runners.
CI
None
=> chore(ci): update runners

.github/workflows/build-cli.yml
The macOS deployment target is used during compilation, which is not done for the CLI as it is just repackaged.
Simplify builds
CI
- None
=> chore: remove macosx deployment target

.github/workflows/build-cli.yml
Previously tightened the permissions, but the `contents: write` permissions should have been kept.
To unblock releases
CI
- None
=> chore(ci): fix cli publish permissions

.github/workflows/build-cli.yml, pact-python-cli/hatch_build.py, pact-python-cli/pyproject.toml
Instead of building separate wheels for each Python version, we now build `py3-none-{platform}` wheels. These can be used by any Python 3 version, now and into the future.
The reason this works is that the Python code is pure Python and only bundles CLIs to be called through Python.
Reduce the burden on PyPI, and simplify packaging in cases where people want to download wheels to install offline.
CI
Ref: #1120
Ref: #1082
=> feat(cli): build abi-agnostic wheels

pact-python-ffi/pyproject.toml
- The `pytest-mock` is not used in testing
- The `typing-extensions` was missing
=> chore(deps): fix optional dependencies

examples/plugins/protobuf/test_consumer.py, src/pact/interaction/_base.py, tests/compatibility_suite/test_v3_consumer.py, tests/compatibility_suite/test_v3_message_consumer.py, tests/compatibility_suite/util/interaction_definition.py, tests/test_http_interaction.py, tests/test_match.py
Instead of having the overloaded function:
- `given(state, *, key, value)`
- `given(state, *, parameters)`
The `given` function's new signature is:
- `given(state, parameters, /, **kwargs)`
In this form, the `state` and (optional) `parameters` must _always_ be positional, and all keyword arguments get used as parameters. This allows for the `parameters` key to be used in the kwargs.
The signature of `Interaction.given` has been updated. The following changes are required:
- Change `given("state", key="user_id", value=123)` to `given("state", user_id=123)`. This can take an arbitrary number of keyword arguments. If the key is not a valid Python keyword argument, use the dictionary input below.
- Change `given("state", parameters={"user_id": 123})` to `given("state", {"user_id": 123})`. …
=> feat!: simplify `given`

src/pact/match/__init__.py
There was a mismatch between the documented default and the actual default in practice.
If you relied on the previous default (undocumented) behaviour, prefer specifying the format explicitly now: `match.datetime(regex="%Y-%m-%dT%H:%M:%S.%f%z")`.
To align the actual behaviour with the documented behaviour.
=> fix: use correct datetime default format

src/pact/verifier.py
The empty state callback provides a mechanism to hook in to the test setup and teardown in a generic way. This was not well handled before.
- pact-foundation/pact-reference#468
=> fix: handle empty state callback

pact-python-cli/pyproject.toml, pact-python-ffi/pyproject.toml, pyproject.toml
Support pre and post releases.
Preparing for Pact Python v3 pre-release.
- #383
=> chore: support pre and post release tags

README.md
Without both of these, either GitHub's rendering or MkDocs' sizing of the mascot is incorrect.
=> docs: set mascot width and height

tests/compatibility_suite/test_v3_matching_rules.py, tests/compatibility_suite/test_v4_matching_rules.py
Implement compatibility suites around matching rules.
- Fixes: #1179 
- Fixes: #1180
=> chore: add v3 matching rules test

.github/workflows/build-cli.yml, .github/workflows/build-ffi.yml, .github/workflows/build.yml, .github/workflows/test.yml
Minor tweak to ensure that the build is not reported as successful unless the deployment is successful (or skipped).
=> chore(ci): add publish as completion dependency

.github/workflows/test.yml
The previous caching did not work as expected.
=> chore(ci): fix prek caching

src/pact/generate/__init__.py, src/pact/match/__init__.py
Define types for the various supported UUID formats.
=> chore: update uuid format names

README.md, pact-python-cli/README.md, pact-python-ffi/README.md
Fix CI badge links. In particular, filter on the main branch by default, and also a fix of the FFI badges linking to the CLI pipelines.
=> docs: fix CI badge links

src/pact/pact.py
Change the default Pact specification from V3 to V4.
Pact instances default to version 4 of the Pact specification (previously used version 3). This should be mostly backwards compatible, but can be reverted by using `with_specification("V3")`.
Version 4 of the Pact specification has been available for a while now, and this will help with its adoption.
=> feat!: default to v4 specification

MIGRATION.md, docs/SUMMARY.md, docs/consumer.md, docs/provider.md, docs/releases.md, mkdocs.yml, src/pact/generate/__init__.py, src/pact/generate/generator.py, src/pact/interaction/_base.py, src/pact/interaction/_http_interaction.py, src/pact/match/__init__.py, src/pact/match/matcher.py, src/pact/verifier.py
Overhaul of the documentation in preparation of the V3 release.
In particular:
- Add a migration guide
- Update the consumer and provider docs with the new V3 interface
- Update the matcher and generator module docs
The abstract `Matcher` and `Generator` classes have been renaned to `AbstractMatcher` and `AbstractGenerator`. This is not going to be a breaking change unless you have created your own matcher or generator.
To help with the adoption of the soon-to-be-released version 3, for both new and existing Pact Python users.
- Resolves: #1222
=> docs: update for v3 and add migration guide

pyproject.toml
Drop the `cffi` package from Pact Python dependencies.
Since the FFI has been moved into its own standalone `pact-python-ffi` package, the core Pact Python library has no need for `cffi`.
=> chore: drop cffi dependency

.github/workflows/build-cli.yml, .github/workflows/build-ffi.yml, .github/workflows/build.yml
Insert a fallback if the release-specific change log cannot be generated.
There was an issue with releasing Pact Python 3.0.1 and Pact Python FFI 0.4.28.2 whereby the release changelog could not be generated (despite the rest of the changelog being generated fine).
This inserts a placeholder to be filled in, as opposed to failing the release entirely.
Ref: https://github.com/pact-foundation/pact-python/actions/runs/18270656326/job/52012475672
=> chore(ci): fix publish step

.github/workflows/labels.yml
Add the `issues: write` permission, which should allow the workflow to actually update the labels.
The workflow was not working.
=> chore(ci): fix labels workflow permissions

pyproject.toml
While they are, for the most part, equivalent, I prefer to avoid using the quotes and use the normalised keys as documented in <https://packaging.python.org/en/latest/specifications/well-known-project-urls/#well-known-labels>.
=> chore(docs): use normalized project url keys
